### ISSUE TITLE
[False positive] Windows Security flags v2.0.0 executable as Trojan:Win32/Wacatac.H!ml

### ISSUE THREAD

**Issue by poetryofcode** [jonasberge/discord-music-presence#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Windows Security flags v2.0.0 executable as Trojan:Win32/Wacatac.H!ml.

### Reproduction Steps

Windows Security flags it automatically after download.

### Expected behavior

It probably shouldn't be flagged as a trojan.

### Screenshots

![Screenshot](https://github.com/jonasberge/discord-music-presence/assets/169371693/0edd4ae3-19e1-441f-9fb7-2fc68df09859)

### Device Info

- Discord Music Presence version: v2.0.0
- Operating system: Windows 11 Pro 23H2 22631.3527

### Additional context

I'd guess it's a false positive but still it put me off from trying out the program for the time being. 

Reporting this to bring it to your awareness, so you can possibly get it fixed.

Cheers.

**Comment by jonasberge** [comment]
Thanks for the report. You are right, it is a false positive, it is a known issue with NSIS installers, here are some links:

- https://nsis.sourceforge.io/NSIS_False_Positives
- https://stackoverflow.com/q/48833995/6748004

I will attach a simple ZIP file containing the program and its libraries to the current release, once I get around to it today, which should be clean and let you try Music Presence without worry. I'll notify you here once I've done that.

I've had Windows 10 Defender flag it as well when I tried the installer on a device other than the development machine, but it didn't happen again for me (and seemingly also not for others) after I reported the false positive to Microsoft, so I just stuck with the NSIS installer for now. Apparently it's still an issue though, thanks for reporting it!

I was going to attach a ZIP file to the next release anyway, for those who prefer it, but I will also look into other ways of packaging the software for Windows that hopefully won't cause false positives like this in the future.

**Comment by jonasberge** [comment]
@poetryofcode I have attached a ZIP release to the latest release, you can find it here:

- https://github.com/jonasberge/discord-music-presence/releases/tag/v2.0.0

Here are also the analysis results for this file:

- https://www.virustotal.com/gui/file/69d4148c96c876ffe07e26635c61815b5cff1a4b9e2486507889ba2a5469193d/detection

Let me know if you have any more questions!

**Comment by poetryofcode** [comment]
> @poetryofcode I have attached a ZIP release to the latest release, you can find it here:
> 
>     * https://github.com/jonasberge/discord-music-presence/releases/tag/v2.0.0
> 
> 
> Here are also the analysis results for this file:
> 
>     * https://www.virustotal.com/gui/file/69d4148c96c876ffe07e26635c61815b5cff1a4b9e2486507889ba2a5469193d/detection
> 
> 
> Let me know if you have any more questions!

Thank you! Works a treat. 

The app is exactly what I was looking for with the Tidal integration.

Keep up the good work, cheers!
