### ISSUE TITLE
Invert song title and artist

### ISSUE THREAD

**Issue by poetryofcode** [jonasberge/discord-music-presence#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

As it stands, the format is always [Song title] - [Artist].

### Solution

It would be great to have an option for users to invert this, so it would show [Artist] - [Song title] in rich presence.

**Comment by jonasberge** [comment]
I'm planning to add more fine-grained controls to configure exactly where which data goes, but this is trivial enough to implement, that I will add a switch for it to the next release in the settings sub menu. Thanks for the suggestion!

**Comment by poetryofcode** [comment]
> I'm planning to add more fine-grained controls to configure exactly where which data goes, but this is trivial enough to implement, that I will add a switch for it to the next release in the settings sub menu. Thanks for the suggestion!

Awesome, cheers. I'll be waiting!

**Comment by jonasberge** [comment]
Implemented in version 2.0.1.
