### ISSUE TITLE
Disclose source code and acknowledge credits 

### ISSUE THREAD

**Issue by purpl3F0x** [jonasberge/discord-music-presence#6]
Hello, I'm seeing that your app is (probably) using lot of my code form the TIDAL-rpc app, and also both of some assets I have created.
All of the above mentioned work are under an MIT license, please disclose the source code and proper references.
Thank You

**Comment by jonasberge** [comment]
Thank you for reaching out.

I have rewritten the application from the ground up and I am currently in the process of reflecting those changes in this repository, that's probably how you have been notified. Please give me some time to complete these changes.

The license in the root of the repository as it is right now acknowledge all authors, licenses and libraries I have used in the rewrite of the application. The releases for version 1.4.1 and 1.4.0-6 on the releases page were built with large parts of your source code, which is attached as a zip file with those releases as "Source code (zip)", which also includes the license.

I will make a release for my rewrite later today (tagged version 2.0.0). You can try it for yourself and you will see that it is impossible that I am using your source code, as it works completely differently from your application. Try using it with Qobuz, Spotify or foobar2000 and you will see that it works with those applications as well. Here are some insights:
- I am not reading the title of the TIDAL desktop app, like your code is.
- I am using system APIs to get the currently playing media, independent of the application. On Windows that's WinRT. On macOS that will be the MediaRemote Framework.
- In light of these changes and to be able to say that all source code is written by myself and only myself, I have decided to rewrite the source code from the ground up. None of your code is used from version 2.0.0 onwards.

Additionally, the MIT license does not force me to disclose source anyway, as far as I am aware.

If you have any questions, please let me know!

**Comment by jonasberge** [comment]
I have archived the fork that was making use of your code here: https://github.com/jonasberge/tidal-discord-presence
